version: '3'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fantacalcio_builder
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5040:5432"

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    #      args:
    #        - DATABASE_URL=postgres://postgres:password@postgres/mydatabase
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/fantacalcio_builder
      #      - DATABASE_URL=postgres://postgres:password@localhost:5040/fantacalcio_builder
      - SQLX_OFFLINE=true
    depends_on:
      - db
    ports:
      - "3000:3000"

  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    environment:
      API_URL: http://api:8080
    depends_on:
      - api
    ports:
      - "5000:80"

volumes:
  postgres_data:
